In [1]:
# Loading the dataset
import pandas as pd
import numpy as np

# Load Dataset
adf = pd.read_csv("../Data/Raw/03_aum_by_fund_house.csv")

# Basic Exploration
print("Shape:", adf.shape)

display(adf.head())

adf.info()

print("\nMissing Values:")
print(adf.isnull().sum())

print("\nColumns:")
print(adf.columns.tolist())

Shape: (90, 5)

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     object
 1   fund_house      90 non-null     object
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.6+ KB

Missing Values:
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

Columns:
['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes']

In [2]:
# Converting 'date' column to datetime
adf["date"] = pd.to_datetime(
    adf["date"],
    errors="coerce"
)

print("Invalid Dates:", adf["date"].isna().sum())

Invalid Dates: 0

In [3]:
# Checking for duplicates based on 'date' and 'fund_house'
duplicates = adf.duplicated(
    subset=["date", "fund_house"]
).sum()

print("Duplicate Records:", duplicates)

Duplicate Records: 0

In [ ]:
# Validating AUM values
print(
    "Invalid AUM Records:",
    (adf["aum_crore"] <= 0).sum()
)

Invalid AUM Records: 0

In [5]:
# Validating Number of Schemes
print(
    "Invalid Number of Schemes:",
    (adf["num_schemes"] <= 0).sum()
)

Invalid Number of Schemes: 0

In [6]:
# Checking for summary statistics of numerical columns
adf.describe()

                      date  aum_lakh_crore     aum_crore  num_schemes
count                   90       90.000000  9.000000e+01    90.000000
mean   2024-02-19 10:40:00        4.352889  4.352889e+05   152.200000
min    2022-03-31 00:00:00        1.050000  1.050000e+05    56.000000
25%    2023-03-31 00:00:00        2.525000  2.525000e+05    95.000000
50%    2024-03-31 00:00:00        3.450000  3.450000e+05   172.500000
75%    2024-12-31 00:00:00        5.675000  5.675000e+05   195.000000
max    2025-12-31 00:00:00       12.500000  1.250000e+06   216.000000
std                    NaN        2.734328  2.734328e+05    52.108832

In [7]:
# Saving the cleaned dataset to a new CSV file in Processed folder
adf.to_csv(
    "../Data/Processed/03_aum_by_fund_house_cleaned.csv",
    index=False
)

print("03_aum_by_fund_house_cleaned.csv saved successfully!")

03_aum_by_fund_house_cleaned.csv saved successfully!